version: 2.1

executors:
  default:
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx2048m
      GRADLE_OPTS: -Xmx1536m

orbs:
  android: circleci/android@0.1.0

commands:
  restore_gradle_cache:
    steps:
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "buildSrc/src/main/java/dependencies/Versions.kt" }}-{{ checksum "buildSrc/src/main/java/dependencies/Deps.kt" }}
            - gradle-cache-{{ checksum "buildSrc/src/main/java/dependencies/Versions.kt" }}-

  save_gradle_cache:
    steps:
      - save_cache:
          key: gradle-cache-{{ checksum "buildSrc/src/main/java/dependencies/Versions.kt" }}-{{ checksum "buildSrc/src/main/java/dependencies/Deps.kt" }}
          paths:
            - ~/.gradle

jobs:
  publish:
    executor: default
    steps:
      - checkout
      - restore_gradle_cache
      - android/restore-build-cache
      - run:
          name: Prepare artifacts
          command: ./gradlew publishToMavenLocal --stacktrace
      - run:
          name: Upload to Bintray
          command: ./gradlew bintrayUpload --stacktrace
workflows:
  version: 2
  publish:
    jobs:
      - publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

