name: Publish to Bintray

on:
  create:

jobs:
  publish:

    runs-on: ubuntu-latest

    if: ${{ github.event.ref_type == 'tag' }}

    env:
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PASS: ${{ secrets.SONATYPE_PASS }}
      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      GPG_SIGNING_PASS: ${{ secrets.GPG_SIGNING_PASS }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build and upload artifacts
        run: ./gradlew publish --stacktrace
